set guicursor=n-v-c:block-Cursor/lCursor-blinkon0,i-ci:ver25-Cursor/lCursor,r-cr:hor20-Cursor/lCursor
set relativenumber
set number
set ignorecase
set smartcase
set ruler
set encoding=utf-8
set scrolloff=2
set title
set confirm
set hidden
set undodir=~/.cache/nvim/undo//
set undofile
set lazyredraw
set swapfile
set dir=~/.cache/nvim/swap//
